#!/usr/bin/env php
<?php
declare(strict_types=1);

use PhpGc\CodeGenerator;
use PhpGc\FilePathAssignorPsr4;
use PhpGc\TemplateEngine\Twig\TwigTemplateEngine;
use PumlParser\Lexer\Lexer;
use PumlParser\Parser\Parser;

foreach ([__DIR__ . '/../../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/../../autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$filePath = $_SERVER['argv'][1];

if (!file_exists($filePath)) {
    fwrite(STDERR, 'File not exists.');

    die(1);
}

if (!str_ends_with($filePath, '.puml')) {
    fwrite(STDERR, 'The file specified is not a plantuml file.');

    die(1);
}

$code_generator = new CodeGenerator(
    TwigTemplateEngine::newInstance(),
    new FilePathAssignorPsr4(require __DIR__ . '/../../composer/autoload_psr4.php'),
    new Parser(Lexer::fromSourceFile($filePath))
);

$code_generator->generateClassFile();
