#!/usr/bin/env php
<?php
declare(strict_types=1);

use Puml2Php\Puml2PhpCompiler;
use Puml2Php\FilePathAssignorPsr4;
use Puml2Php\TemplateEngine\Twig\TwigTemplateEngine;
use PumlParser\Parser\Parser;

foreach ([ __DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$pumlFilePath = $_SERVER['argv'][1];

if (!file_exists($pumlFilePath)) {
    fwrite(STDERR, 'File not exists.');

    die(1);
}

if (!str_ends_with($pumlFilePath, '.puml')) {
    fwrite(STDERR, 'The file specified is not a plantuml file.');

    die(1);
}

foreach ([__DIR__ . '/vendor/composer/autoload_psr4.php', __DIR__ . '/../../composer/autoload_psr4.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$psr4map = require __DIR__ . '/vendor/composer/autoload_psr4.php';

$compiler = new Puml2PhpCompiler(TwigTemplateEngine::newInstance(), new FilePathAssignorPsr4($psr4map), new Parser());

$compiler->exec($pumlFilePath, true);
